env:
  es6: true
  browser: true
  commonjs: true
  node: true
  jest: true

extends: ['htmlacademy/es6', 'plugin:react/recommended']

parser: '@typescript-eslint/parser'

rules: {
  'no-invalid-this': 0,
  'react-hooks/rules-of-hooks': 'error',
  'react-hooks/exhaustive-deps': 'warn'
}

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2019
  sourceType: module

plugins: ['react', 'react-hooks']

settings:
  react:
    version: '16'
