env:
  es6: true
  browser: true
  commonjs: true
  node: true
  jest: true

extends: ['htmlacademy/es6', 'plugin:react/recommended']

parser: 'babel-eslint'

rules: {
  'no-invalid-this': 0
}

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2019
  sourceType: module

plugins: ['react']

settings:
  react:
    version: '16'
