export const ActionType = Object.freeze({
  AUTH_FAIL: `AUTHENTICATION_FAILURE`,
  AUTH_REQUIRED: `AUTHORIZATION_REQUIRED`,
  CHANGE_GENRE: `CHANGE_GENRE`,
  GET_USER_DATA: `GET_USER_DATA`,
  LOAD_MOVIES: `LOAD_MOVIES`
});
